clippy_task:
    container:
        image: rustlang/rust:nightly
    component_script: rustup component add clippy
    update_script: cargo +nightly update
    toolchain_cache:
        folder: $RUSTUP_HOME
        fingerprint_script: rustc +nightly --version
    cargo_cache:
        folder: $CARGO_HOME/registry
        fingerprint_script: cat Cargo.lock
    fmt_script: cargo +nightly clippy

rustfmt_task:
    container:
        image: rustlang/rust:nightly
    component_script: rustup component add rustfmt
    fmt_script: cargo fmt --all -- --check

linux_task:
    container:
      image: rust:latest
    matrix:
        - env:
              RUSTVER: 1.32.0
        - env:
              RUSTVER: stable
        - allow_failures: true
          env:
              RUSTVER: nightly
    rustup_script: rustup toolchain install $RUSTVER
    toolchain_cache:
        folder: $RUSTUP_HOME
        fingerprint_script: rustc +$RUSTVER --version
    update_script: cargo +$RUSTVER update
    cargo_cache:
        folder: $CARGO_HOME/registry
        fingerprint_script: cat Cargo.lock
    build_script: cargo +$RUSTVER build
    test_script: cargo +$RUSTVER test
    before_cache_script: rm -rf $CARGO_HOME/registry/index

windows_task:
    container:
        image: cirrusci/windowsservercore:2019
    install_script: choco install -y rust
    update_script: cargo update
    cargo_cache:
        folder: $CARGO_HOME/registry
        fingerprint_script: cat Cargo.lock
    build_script: cargo build
    test_script: cargo test
    before_cache_script: del /S /Q $CARGO_HOME\registry\index
