[package]
name = "machine-id"
version = "0.4.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
license = "BSD-3-Clause"
description = """
Library to get a UUID specific to the machine.
"""
repository = "https://github.com/mathstuf/rust-machine-id"
documentation = "https://docs.rs/machine-id/~0.4"
keywords = ["uuid"]
edition = "2018"

[dependencies]
lazy_static = "^1.0"
log = "~0.4"
thiserror = "^1.0"
# https://github.com/retep998/winapi-rs/issues/214
#winapi = "~0.2.4"
#advapi32-sys = "~0.1.2"

uuid = { version = "~0.8", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
winreg = "~0.7"
rust_win32error = "~0.8"
